### ISSUE TITLE
Cognos analytics instance deployment failed

### ISSUE THREAD

**Issue by duomotomo** [IBM/cloud-pak-deployer#78]
I have tried to deploy cognos analytics instance with ocp_existing profile and CP4D 4.5. While ansible summary status was successful, in CP4D cognos instance status is Failed. 

The following excerpt could be found in ibm-cognos-addon-sp-deployment-xx log:

[2022-08-04T09:06:57.799] [INFO] serviceprovidericp4d - Loaded the jwt pubkey:
[2022-08-04T09:06:57.802] [INFO] serviceprovidericp4d - Payload : , {"username":"admin","role":"Admin","permissions":["administrator","can_provision","manage_catalog","create_project","create_space","author_governance_artifacts","manage_governance_workflow","view_governance_artifacts","manage_categories","manage_glossary","manage_quality","manage_discovery","manage_metadata_import","access_catalog","view_quality"],"groups":[10000],"sub":"admin","iss":"KNOXSSO","aud":"DSX","uid":"1000330999","authenticator":"default","display_name":"admin","iat":1659602864,"exp":1659646028,"accessToken":"VALID_TOKEN","csrf_token":"VALID_TOKEN"}
[2022-08-04T09:06:57.803] [INFO] serviceprovidericp4d - API: /v1/provision/
[2022-08-04T09:06:57.803] [INFO] serviceprovidericp4d - provision controller for instance ID: 1659604017629154
[2022-08-04T09:06:58.655] [ERROR] serviceprovidericp4d - TypeError: Cannot read properties of undefined (reading 'entity')
    at _updateConnectionInfo (/app/server/controllers/instances.js:114:81)
    at Object.module.exports._updateOverrides (/app/server/controllers/instances.js:213:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports.provisionInstance (/app/server/controllers/instances.js:41:17)
    at async /app/server/helpers/controller_wrapper.js:41:20

Openshift 4.10
CP4D 4.5

**Comment by duomotomo** [comment]
![cognos_instance_status](https://user-images.githubusercontent.com/29203123/182922260-e0c2ca43-afb0-4e4e-a24d-6b22537e0aff.PNG)
[configs.zip](https://github.com/IBM/cloud-pak-deployer/files/9262219/configs.zip)

**Comment by duomotomo** [comment]
added configs and screenshot.
All other components was installed without any problem.
Also as I see it related db2 cognos instance was also installled successfully

**Comment by duomotomo** [comment]
![instances](https://user-images.githubusercontent.com/29203123/182922564-fd6b5f80-e5c5-4a94-8843-8caac861f899.png)

**Comment by arthurlaimbock** [comment]
@duomotomo can you share your deployer configuration? I would like to see if I can replicate the issue. I just completed a provisioning of OpenShift 4.10 + CP4D 4.5 with DB2 + CA on IBM Cloud, and this completed without issues.

**Comment by duomotomo** [comment]
[configs.zip](https://github.com/IBM/cloud-pak-deployer/files/9266476/configs.zip)
Deployer configs

**Comment by fketelaars** [comment]
This should be fixed with #281
